FROM joyzoursky/python-chromedriver:3.8

WORKDIR /src
COPY requirements.txt /src
RUN pip install -r requirements.txt

COPY . /src

RUN chmod a+x /src/docker/*.sh

CMD ["/src/docker/celery.sh", "celery"]